name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-run-cleanup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3


    # Build the Docker image
    - name: Build Docker image
      run: docker build -t hello-world .

    # Run the Docker container
    - name: Run Docker container
      run: |
        docker run -d --name hello-container -p 5000:5000 hello-world
        echo "Container started. Waiting for 30 seconds..."
        sleep 30

    # Test the application by retrieving the URL
    - name: Test application
      run: |
        curl -s http://localhost:5000 || echo "Failed to connect to the application."

    # Stop and remove the Docker container
    - name: Cleanup Docker container
      run: |
        docker stop hello-container
        docker rm hello-container
      
